In [50]:
print('Hello World!')

Hello World!

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
df = pd.read_csv("/content/tracxn.csv",encoding='latin-1')

In [53]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,Payments,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,Alternative Lending,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,Electric Vehicles,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M"
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",NaN,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,Road Transport Tech,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",NaN,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,Logistics Tech,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025"

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             71 non-null     object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          117 non-null    object
 13  top_investors_2          117 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
dtypes: int64(2), object(17)
memory usage: 17.6+ KB

In [55]:
df.isnull().sum()

Rank                        0
Company                     0
company_link                0
company_info                0
round_led_by               47
company_background          0
founded_year                0
location                    0
country                     0
stage                       0
primary_sector              0
time_to_unicorn             0
top_investors_1             1
top_investors_2             1
annual_revenue              0
valuation                   2
total_funding_till_date    31
employee_count             15
latest_funding_round        0
dtype: int64

In [56]:
df[df['top_investors_1'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",NaN,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,NaN,NaN,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025"

In [57]:
df[df['top_investors_2'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",NaN,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,NaN,NaN,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025"

In [58]:
df[df['round_led_by'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",NaN,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,Road Transport Tech,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",NaN,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,Logistics Tech,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025"
10,108,Molbio Diagnostics,https://tracxn.com/d/companies/molbio-diagnost...,Molbio Diagnostics joined the Unicorn Club on ...,NaN,Provider of molecular diagnostic solutions for...,2000,Salcete,India,Series C,Infectious Diseases,22 years 8 months,Genomics,Temasek,"?337Cr as on Mar 31, 2023","$1.6B as on Sep 26, 2022",$124M,"698 as on Mar 31, 2025","Grant (prize money), 2023"
11,107,Tata 1mg,https://tracxn.com/d/companies/tata-1mg/__dSVq...,"Tata 1mg joined the Unicorn Club on Sep 06, 2022",NaN,Provider of an online pharmacy with doctor lis...,2015,Delhi,India,Acquired,Healthcare Booking Platforms,7 years 8 months,HBM Healthcare Investments,Maverick Ventures,"?1,990Cr as on Mar 31, 2024","$1.25B as on Sep 06, 2022",$231M,"4,360 as on Feb 28, 2025","Series D, Sep 02, 2022, $40.8M"
12,106,Shiprocket,https://tracxn.com/d/companies/shiprocket/__GE...,"Shiprocket joined the Unicorn Club on Aug 17, ...",NaN,E-commerce shipping and fulfillment platform t...,2012,Gurugram,India,Series E,Logistics Tech,10 years 7 months,E-Commerce Enablers,Brands Tech,"?1,360Cr as on Mar 31, 2024","?10,200Cr as on Mar 07, 2025",$349M,"805 as on Mar 31, 2025","Series E, Dec 27, 2024, $26M"
14,104,LeadSquared,https://tracxn.com/d/companies/leadsquared/__G...,"LeadSquared joined the Unicorn Club on Jun 21,...",NaN,Cloud based platform offering sales CRM and ma...,2011,Bengaluru,India,Series C,Sales Force Automation,11 years 5 months,MarketingTech,Field Force Automation,"?325Cr as on Mar 31, 2024","?7,200Cr as on Nov 03, 2022",$204M,NaN,"Series C, Jun 12, 2022, $153M"
25,93,Uniphore,https://tracxn.com/d/companies/uniphore/__qc0T...,"Uniphore joined the Unicorn Club on Feb 16, 2022",NaN,AI and cloud-based platform offering conversat...,2008,Palo Alto,United States,Series E,Speech and Voice Recognition,14 years 1 month,Customer Service Software,Sales Force Automation,"?314Cr as on Mar 31, 2024",$1.67B - $3.12B,$657M,"363 as on Mar 31, 2025","Series E, Jan 28, 2022, $400M"
27,91,ElasticRun,https://tracxn.com/d/companies/elasticrun/__D5...,"ElasticRun joined the Unicorn Club on Feb 08, ...",NaN,Provider of B2B e-commerce and logistics solut...,2014,Pune,India,Series E,E-Commerce Enablers,8 years 1 month,Rural Ecommerce,In Store Retail Tech,"?2,540Cr as on Mar 31, 2024","$800M as on Jun 07, 2024",$462M,"1,253 as on Feb 28, 2025","Series E, Feb 07, 2022, $330M"
30,88,Darwinbox,https://tracxn.com/d/companies/darwinbox/__ZCn...,"Darwinbox joined the Unicorn Club on Jan 25, 2022",NaN,Cloud-based suite solutions for HR management....,2015,Hyderabad,India,Series D,HRTech,7 years,TCV,KKR,"?393Cr as on Mar 31, 2024","?8,410Cr as on Mar 12, 2025",$280M,"1,049 as on Jan 31, 2025","Series D, Mar 05, 2025, $140M"
33,85,Mamaearth,https://tracxn.com/d/companies/mamaearth/__e9I...,"Mamaearth joined the Unicorn Club on Dec 29, 2021",NaN,Online brand offering multi-category natural s...,2016,Gurugram,India,Public,Beauty & Personal Care Products,5 years 11 months,Beauty Tech,Sofina,"?1,970Cr as on Mar 31, 2024",$89.4M,NaN,"958 as on Feb 28, 2025","Angel, Sep 13, 2022, $755K"
34,84,GlobalBees,https://tracxn.com/d/companies/globalbees/__9K...,"GlobalBees joined the Unicorn Club on Dec 19, ...",NaN,Platform acquiring e-commerce brands. The comp...,2021,Delhi,India,Series B,Brands Tech,11 months,E-Commerce Enablers,ChrysCapital,"?20.8Cr as on Mar 31, 2024","?8,400Cr as on Dec 30, 2021",$186M,"230 as on Feb 28, 2025","Conventional Debt, Feb 06, 2024, $18.1M"
39,79,Mensa Brands,https://tracxn.com/d/companies/mensa-brands/__...,Mensa Brands joined the Unicorn Club on Nov 16...,NaN,"Crafts global health, wellness, and lifestyle ...",2021,Bengaluru,India,Series B,E-Commerce Enablers,10 months,Brands Tech,Norwest Venture Partners,"?598Cr as on Mar 31, 2024","$967M as on Oct 16, 2024",$207M,"427 as on Oct 31, 2024","Angel, May 07, 2024, $802K"
41,77,MyGlamm,https://tracxn.com/d/companies/myglamm/__o9Zf4...,"MyGlamm joined the Unicorn Club on Nov 09, 2021",NaN,Online store offering multi-category beauty pr...,2015,Mumbai,India,Series C,Beauty & Personal Care Products,6 years 10 months,Beauty Tech,Bessemer Venture Partners,"$100M as on Mar 18, 2021",$106M,NaN,"411 as on Dec 31, 2024","Conventional Debt, Sep 28, 2021, $21M"
42,76,Upstox,https://tracxn.com/d/companies/upstox/__41x3SA...,"Upstox joined the Unicorn Club on Nov 01, 2021",NaN,Online trading and investing solutions. It ena...,2009,Mumbai,India,Series C,Investment Tech,12 years 10 months,Tiger Global Management,Innoven Capital,"?1,310Cr as on Mar 31, 2024","?23,800Cr as on Sep 20, 2022",$220M,"588 as on Feb 28, 2025","Series C, Sep 16, 2022"
44,74,PharmEasy,https://tracxn.com/d/companies/pharmeasy/__2Q7...,"PharmEasy joined the Unicorn Club on Oct 19, 2021",NaN,Consumer healthcare platform offing a variety ...,2015,Mumbai,India,Series F,Healthcare Booking Platforms,6 years 9 months,TPG,Temasek,"?104Cr as on Mar 31, 2024","$456M as on Dec 26, 2024",$688M,"481 as on Mar 31, 2025","Series F, May 10, 2022"
45,73,MobiKwik,https://tracxn.com/d/companies/mobikwik/__chMM...,"MobiKwik joined the Unicorn Club on Oct 12, 2021",NaN,Financial technology company that provides a m...,2009,Gurugram,India,Public,Payments,12 years 9 months,ADIA,American Express Ventures,"?543Cr as on Mar 31, 2022",$284M,NaN,"735 as on Dec 31, 2024","Conventional Debt, Mar 28, 2024, $6M"
46,72,CarDekho,https://tracxn.com/d/companies/cardekho/__LzK0...,"CarDekho joined the Unicorn Club on Oct 12, 2021",NaN,Online forum for car buyers to list old vehicl...,2008,Jaipur,India,Series C,Auto E-Commerce & Content,13 years 9 months,Auto Retail & Aftersales,Navis Capital Partners,"$1.2B as on Oct 13, 2021",$60M,NaN,"2,387 as on Feb 28, 2025","Series C, Dec 11, 2024, $60M"
47,71,Rebel Foods,https://tracxn.com/d/companies/rebel-foods/__c...,"Rebel Foods joined the Unicorn Club on Oct 07,...",NaN,Provider of virtual restaurant network for foo...,2010,Mumbai,India,Series G,Food Tech,11 years 9 months,Goldman Sachs,KKR,"?13,800Cr as on Apr 21, 2025",$587M,NaN,"6,753 as on Feb 28, 2025","Series G, Apr 22, 2025, $25M"
51,67,Apna,https://tracxn.com/d/companies/apna/__UTcOz_R9...,"Apna joined the Unicorn Club on Sep 16, 2021",NaN,Provider of a job platform connecting job seek...,2019,Bengaluru,India,Series C,HRTech,2 years 8 months,Maverick Ventures,Insight Partners,"$1.1B as on Sep 16, 2021",$194M,NaN,"737 as on Feb 28, 2025","Series C, Sep 15, 2021, $100M"
53,65,Zetwerk,https://tracxn.com/d/companies/zetwerk/__n78BE...,"Zetwerk joined the Unicorn Club on Aug 20, 2021",NaN,Provider of manufacturing services and supply ...,2018,Bengaluru,India,Series F,B2B E-Commerce,3 years 7 months,Manufacturing Tech,Baillie Gifford,"?14,600Cr as on Mar 31, 2024","?25,400Cr as on Mar 21, 2025",$768M,"1,049 as on Oct 31, 2024","Series F, Dec 12, 2024, $70M"
55,63,CoinDCX,https://tracxn.com/d/companies/coindcx/__F--po...,"CoinDCX joined the Unicorn Club on Aug 10, 2021",NaN,Developer of an app-based exchange platform fo...,2018,Mumbai,India,Series D,Cryptocurrencies,3 years 7 months,Bain Capital Ventures,Jump Capital,"?394Cr as on Mar 31, 2024","$2.15B as on Apr 19, 2022",$247M,"103 as on Jan 31, 2025","Series D, Mar 29, 2022, $135M"
56,62,upGrad,https://platform.tracxn.com/a/d/company/-icjnE...,"upGrad joined the Unicorn Club on Aug 09, 2021",NaN,Online education platform offering professiona...,2015,Mumbai,India,Series C,Continued Learning,6 years 7 months,IFC Asset Management Company,Temasek,"?1,550Cr as on Mar 31, 2024","?16,000Cr as on Nov 12, 2024",$329M,"8,090 as on Dec 31, 2024","Series C, Oct 21, 2024, $60M"
60,58,Droom,https://tracxn.com/d/companies/droom/__r5sS3yn...,"Droom joined the Unicorn Club on Jul 28, 2021 ...",NaN,AI-powered used vehicle dealer. Users can buy ...,2014,Gurugram,India,Series G,Auto E-Commerce & Content,7 years 6 months,Auto Retail & Aftersales,Digital Garage,"?90Cr as on Mar 31, 2024","?3,100Cr as on Mar 28, 2025",$344M,"139 as on Feb 28, 2025","Series G, Mar 26, 2025, $3M"
61,57,BlackBuck,https://tracxn.com/d/companies/blackbuck/__pGe...,"BlackBuck joined the Unicorn Club on Jul 22, 2021",NaN,A digital trucking platform that connects flee...,2015,Bengaluru,India,Public,Logistics Tech,6 years 6 months,Wellington,Goldman Sachs,"?317Cr as on Mar 31, 2024",$359M,NaN,"1,608 as on Feb 28, 2025","Conventional Debt, Jul 18, 2022"
62,56,Blinkit,https://tracxn.com/d/companies/blinkit/__pdyje...,"Blinkit joined the Unicorn Club on Jun 30, 2021",NaN,Online platform offering ultra-fast grocery su...,2013,Gurugram,India,Acquired,Online Grocery,8 years 5 months,KTB Ventures,SoftBank Group,"?1,930Cr as on Mar 31, 2024","$13B as on Apr 26, 2024",$757M,"5,054 as on Dec 31, 2024","Conventional Debt, Mar 11, 2022, $150M"
68,50,ShareChat,https://tracxn.com/d/companies/sharechat/__E42...,"ShareChat joined the Unicorn Club on Apr 08, 2021",NaN,App-based social network platform for sharing ...,2015,Bengaluru,India,Series H,Vernacular Platforms,6 years 3 months,Social Platforms,HarbourVest Partners,"$1.5B as on Dec 20, 2023",$1.23B,NaN,"589 as on Nov 30, 2024","Conventional Debt, Aug 03, 2024, $16M"
72,46,Meesho,https://tracxn.com/d/companies/meesho/__h-YKqJ...,"Meesho joined the Unicorn Club on Apr 05, 2021",NaN,Online marketplace offering multi-category pro...,2015,Bengaluru,India,Series F,Horizontal E-Commerce,6 years 3 months,WestBridge Capital,Fidelity Investments,"?9.39Cr as on Mar 31, 2024","$3.9B as on Mar 25, 2024",$1.36B,"1,588 as on Sep 30, 2024","Series F, Jan 27, 2025"
75,43,Innovaccer,https://tracxn.com/d/companies/innovaccer/__kv...,"Innovaccer joined the Unicorn Club on Feb 24, ...",NaN,Cloud-based data analytics platform for health...,2014,San Francisco,United States,Series F,Healthcare Payer Tech,7 years 1 month,Healthcare IT,WestBridge Capital,"?354Cr as on Mar 31, 2024",$2.13B - $4.06B,$675M,"1,003 as on Sep 30, 2024","Series F, Jan 09, 2025"
77,41,VerSe,https://tracxn.com/d/companies/verse/__-RHXs5A...,"VerSe joined the Unicorn Club on Dec 22, 2020",NaN,Developer of a short-video platform and techno...,2007,Bengaluru,India,Series J,Vernacular Platforms,13 years 11 months,Social Platforms,Internet First Media,"?1,260Cr as on Mar 31, 2024","$2.9B as on Aug 30, 2024",$2.01B,"696 as on Feb 28, 2025","Conventional Debt, Feb 07, 2024, $6.02M"
79,39,Zenoti,https://tracxn.com/d/companies/zenoti/__Bz5bIW...,"Zenoti joined the Unicorn Club on Dec 15, 2020",NaN,Cloud-based business management software. The ...,2010,Bellevue,United States,Series D,SME Business Management Software,10 years 11 months,Beauty Tech,Enterprise Resource Planning,"$1.5B as on Jun 07, 2021",$331M,NaN,"787 as on Oct 31, 2024","Series D, Jun 02, 2021, $80M"
80,38,PhonePe,https://tracxn.com/d/companies/phonepe/__Q_bwa...,"PhonePe joined the Unicorn Club on Dec 03, 2020",NaN,Card-linked wallet payment solution for consum...,2012,Bengaluru,India,Acquired,Payments,8 years 11 months,General Atlantic,TVS Capital Funds,"?5,720Cr as on Mar 31, 2024","?1,04,000Cr as on May 31, 2023",$1.01B,"910 as on Jan 31, 2025","Series D, Jan 19, 2023, $658M"
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",NaN,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,NaN,NaN,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025"
87,31,OYO,https://tracxn.com/d/companies/oyo/__4WYOfbQ8d...,"OYO joined the Unicorn Club on Apr 15, 2020",NaN,Provider of online accommodation booking marke...,2012,Gurugram,India,Series G,Online Travel,8 years 3 months,Fidelity Investments,Khazanah Nasional Berhad,"?5,540Cr as on Mar 31, 2024","?36,000Cr as on Jan 03, 2025",$3.47B,"1,191 as on Feb 28, 2025","Series G, Dec 15, 2024, $58.9M"
89,29,FirstCry,https://tracxn.com/d/companies/firstcry/__wxnu...,"FirstCry joined the Unicorn Club on Feb 07, 2020",NaN,Online retailer offering multi-category baby p...,2010,Pune,India,Public,Mom & Baby Care,10 years 1 month,ChrysCapital,New Enterprise Associates,$513M,"6,895 as on Sep 30, 2024",NaN,NaN,"Series E, Mar 27, 2021, $13.1M"
91,27,Lenskart,https://tracxn.com/d/companies/lenskart/___iTt...,"Lenskart joined the Unicorn Club on Dec 20, 2019",NaN,"Online brand offering eyewear for men, women a...",2010,Gurugram,India,Series I,Fashion Tech,9 years 11 months,ChrysCapital,TPG,"?5,610Cr as on Mar 31, 2024","$5.6B as on Nov 05, 2024",$1.08B,"41 as on Feb 28, 2025","Series I, Jul 21, 2023, $18.2M"
94,24,CitiusTech,https://tracxn.com/d/companies/citiustech/__Hh...,"CitiusTech joined the Unicorn Club on Jul 12, ...",NaN,CitiusTech offers analytical solutions and tec...,2005,Mumbai,India,Acquired,Healthcare IT,14 years 6 months,Bain Capital Private Equity,General Atlantic,"?3,550Cr as on Mar 31, 2024","$2.2B as on Mar 16, 2022",$1.07B,"5,369 as on Nov 30, 2024","PE, Oct 20, 2022, $960M"
96,22,Druva,https://tracxn.com/d/companies/druva/__AJfABjH...,"Druva joined the Unicorn Club on Jun 20, 2019",NaN,Cloud data platform offering data backup and p...,2008,Santa Clara,United States,Series H,Cybersecurity,11 years 5 months,IT Operations,Enterprise Storage,"$48.9M as on Mar 31, 2018","$2B as on Apr 19, 2021",$475M,"314 as on Dec 31, 2023","Series H, Apr 19, 2021, $147M"
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",NaN,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,Sales Force Automation,23 years 3 months,Enterprise Collaboration,Customer Service Software,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025"
98,20,Dream11,https://tracxn.com/d/companies/dream11/__1dAVn...,"Dream11 joined the Unicorn Club on Apr 09, 2019",NaN,Online fantasy sports platform that allows use...,2008,Mumbai,India,Series D,Sports Tech,11 years 3 months,Tencent,Multiples Alternate Asset Management,"?6,580Cr as on Mar 31, 2023","$8B as on Nov 26, 2021",$100M,"1,231 as on Feb 28, 2025","Series D, Sep 06, 2018, $100M"
100,18,Delhivery,https://tracxn.com/d/companies/delhivery/__es0...,"Delhivery joined the Unicorn Club on Mar 07, 2019",NaN,"Integrated logistics provider offering parcel,...",2011,Gurugram,India,Public,Logistics Tech,8 years 2 months,E-Commerce Enablers,CPP Investments,"?8,590Cr as on Mar 31, 2024",$1.25B,NaN,"24,590 as on Feb 28, 2025","Series H, Dec 08, 2021, $98.8M"
101,17,BillDesk,https://tracxn.com/d/companies/billdesk/__JJVw...,"BillDesk joined the Unicorn Club on Nov 16, 2018",NaN,Provider of an online payment gateway platform...,2000,Mumbai,India,Series D,Payments,18 years 10 months,General Atlantic,Temasek,"?2,770Cr as on Mar 31, 2023","?11,400Cr as on Feb 15, 2019",$186M,"749 as on Feb 28, 2025","Series D, Jan 17, 2019, $84.8M"
103,15,Freshworks,https://tracxn.com/d/companies/freshworks/__sd...,"Freshworks joined the Unicorn Club on Jul 31, ...",NaN,Cloud-based business process management suite ...,2010,San Mateo,United States,Public,Customer Service Software,8 years 6 months,Sales Force Automation,MarketingTech,"$720M as on Dec 31, 2024",$499M,NaN,"4,400 as on Dec 31, 2024","Series H, Nov 04, 2019, $250M"
104,14,Policybazaar,https://tracxn.com/d/companies/policybazaar/__...,Policybazaar joined the Unicorn Club on Jun 25...,NaN,"Online platform for insurance buyers in India,...",2008,Gurugram,India,Late Stage,Internet First Insurance Platforms,10 years 5 months,Premji Invest,Burman Family Holdings,"?3,820Cr as on Mar 31, 2024","22,635 as on Feb 28, 2025",NaN,NaN,"Post IPO, Oct 14, 2017, $7.69M"
106,12,BYJU'S,https://tracxn.com/d/companies/byjus/__l-UnVup...,"BYJU'S joined the Unicorn Club on Mar 14, 2018",NaN,Online learning platform offering educational ...,2011,Bengaluru,India,Series F,K-12 EdTech,7 years 2 months,Test Preparation Tech,CPP Investments,"$120M as on Jun 04, 2024",$4.45B,NaN,"4 as on Aug 31, 2024","Conventional Debt, May 12, 2023, $250M"
111,7,Ola,https://tracxn.com/d/companies/ola/__gkN0nw281...,"Ola joined the Unicorn Club on Nov 18, 2015",NaN,App-based personal transportation booking plat...,2010,Bengaluru,India,Series J,Road Transport Tech,5 years 10 months,HBM Partners,Odenn Ventures,"?2,200Cr as on Mar 31, 2024","$2B as on Nov 04, 2024",$3.84B,"538 as on Jan 31, 2025","Series J, Feb 22, 2022, $20M"
114,4,Snapdeal,https://platform.tracxn.com/a/d/company/hIjt4a...,"Snapdeal joined the Unicorn Club on May 20, 2014",NaN,Online marketplace platform offering fashion a...,2010,Delhi,India,Series H,Horizontal E-Commerce,4 years 4 months,New Enterprise Associates,BlackRock,"?385Cr as on Mar 31, 2024","$4.8B as on Aug 02, 2015",$1.77B,"277 as on Mar 31, 2025","Angel, Jul 23, 2019"
116,2,Flipkart,https://tracxn.com/d/companies/flipkart/__pEY5...,"Flipkart joined the Unicorn Club on Aug 24, 2012",NaN,Online marketplace platform offering multi-cat...,2007,Bengaluru,India,Acquired,Horizontal E-Commerce,5 years 7 months,CPP Investments,Vulcan Capital,"?70,800Cr as on Mar 31, 2024","$36B as on May 25, 2024",$12.1B,"7,129 as on Feb 28, 2025","Series J, May 25, 2024, $350M"

In [59]:
df['round_led_by'].fillna("Unknown", inplace=True)

<ipython-input-59-3642406742>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['round_led_by'].fillna("Unknown", inplace=True)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          117 non-null    object
 13  top_investors_2          117 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
dtypes: int64(2), object(17)
memory usage: 17.6+ KB

In [61]:
df[(df['top_investors_1'].isna() & df['top_investors_2'].isna())]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,NaN,NaN,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025"

In [62]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,Payments,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,Alternative Lending,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,Electric Vehicles,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M"
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,Road Transport Tech,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,Logistics Tech,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025"

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          117 non-null    object
 13  top_investors_2          117 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
dtypes: int64(2), object(17)
memory usage: 17.6+ KB

In [69]:
df['top_investors_1'].fillna("Unknown", inplace = True)
df['top_investors_2'].fillna("Unknown", inplace = True)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
dtypes: int64(2), object(17)
memory usage: 17.6+ KB

In [71]:
df[df['valuation'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,Unknown,Unknown,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025"
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,Sales Force Automation,23 years 3 months,Enterprise Collaboration,Customer Service Software,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025"

In [72]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,Payments,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,Alternative Lending,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,Electric Vehicles,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M"
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,Road Transport Tech,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,Logistics Tech,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025"

In [74]:
import re

In [116]:
df['unicorn_year'] = df.apply(
    lambda row: row['founded_year'] + (
        (int(re.search(r'(\d+)\s+years?', row['time_to_unicorn']).group(1)) if re.search(r'(\d+)\s+years?', row['time_to_unicorn']) else 0) +
        (1 if (int(re.search(r'(\d+)\s+months?', row['time_to_unicorn']).group(1)) if re.search(r'(\d+)\s+months?', row['time_to_unicorn']) else 0) >= 6 else 0)
    ),
    axis=1
).astype('Int64')

In [110]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,Payments,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,Alternative Lending,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,Electric Vehicles,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,Road Transport Tech,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,Logistics Tech,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
dtypes: Int64(1), int64(2), object(17)
memory usage: 18.7+ KB

In [113]:
df[df['valuation'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,primary_sector,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,Investment Tech,10 years 5 months,Unknown,Unknown,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025",2020
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,Sales Force Automation,23 years 3 months,Enterprise Collaboration,Customer Service Software,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025",2019

In [115]:
df['employee_count']

0      1,015 as on Feb 28, 2025
1        709 as on Feb 28, 2025
2      1,630 as on Mar 31, 2025
3        671 as on Feb 28, 2025
4      2,041 as on Feb 28, 2025
                 ...
113       74 as on Feb 28, 2025
114      277 as on Mar 31, 2025
115    2,312 as on Sep 30, 2024
116    7,129 as on Feb 28, 2025
117                         NaN
Name: employee_count, Length: 118, dtype: object

In [125]:
# Extract date string after 'as on'
df['employee_count_date'] = df['employee_count'].apply(
    lambda x: re.search(r'as on (.+)', str(x)).group(1) if isinstance(x, str) and re.search(r'as on (.+)', str(x)) else pd.NA
)

In [126]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,"Feb 28, 2025"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,"Feb 28, 2025"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,"Mar 31, 2025"
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,"Feb 28, 2025"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,"Feb 28, 2025"

In [127]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    object
dtypes: Int64(1), int64(2), object(18)
memory usage: 19.6+ KB

In [128]:
df[df['employee_count_date'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date
9,109,boAt,https://tracxn.com/d/companies/boat/__1-6OVEvW...,"boAt joined the Unicorn Club on Oct 28, 2022 a...",Warburg Pincus,Platform offering wearable audio devices. Its ...,2016,Gurugram,India,Series C,...,6 years 9 months,Audio Tech,Wearable Technology,"?10,800Cr as on Dec 02, 2022",$171M,"952 as on Feb 28, 2025",NaN,"Angel, Feb 01, 2024",2023,<NA>
13,105,OneCard,https://tracxn.com/d/companies/onecard/__wf9zb...,"OneCard joined the Unicorn Club on Jul 04, 202...",Temasek,Provider of a premium metal credit card with a...,2019,Pune,India,Series D,...,3 years 6 months,GIC,Temasek,"?11,600Cr as on Nov 18, 2024",$262M,"954 as on Jan 31, 2025",NaN,"Series D, Nov 18, 2024, $28.5M",2023,<NA>
14,104,LeadSquared,https://tracxn.com/d/companies/leadsquared/__G...,"LeadSquared joined the Unicorn Club on Jun 21,...",Unknown,Cloud based platform offering sales CRM and ma...,2011,Bengaluru,India,Series C,...,11 years 5 months,MarketingTech,Field Force Automation,"?325Cr as on Mar 31, 2024","?7,200Cr as on Nov 03, 2022",$204M,NaN,"Series C, Jun 12, 2022, $153M",2022,<NA>
16,102,Physics Wallah,https://tracxn.com/d/companies/physics-wallah/...,Physics Wallah joined the Unicorn Club on Jun ...,WestBridge Capital,"Online platform offering live courses for JEE,...",2020,Noida,India,Series B,...,2 years 5 months,Test Preparation Tech,WestBridge Capital,"$3.7B as on Feb 11, 2025",$312M,"11,464 as on Feb 28, 2025",NaN,"Series B, Sep 20, 2024, $210M",2022,<NA>
18,100,Open,https://tracxn.com/d/companies/open/__Tivm52sB...,"Open joined the Unicorn Club on May 02, 2022 a...",India Infoline,SaaS-based digital bank for startups and enter...,2017,Bengaluru,India,Series D,...,5 years 4 months,Temasek,Recruit Strategic Partners,"?7,300Cr as on Jun 01, 2022",$186M,"289 as on Mar 31, 2025",NaN,"Series D, May 02, 2022, $50M",2022,<NA>
22,96,Amagi,https://tracxn.com/d/companies/amagi/__EroEsPU...,"Amagi joined the Unicorn Club on Mar 16, 2022 ...",Accel,Cloud based CTV advertising platform for enter...,2008,Bengaluru,India,Series F,...,14 years 2 months,Tech for Film & TV,OTT Video,"?11,600Cr as on Nov 13, 2022",$359M,NaN,NaN,"Series F, Nov 01, 2022, $100M",2022,<NA>
24,94,Hasura,https://tracxn.com/d/companies/hasura/__SMK3S7...,"Hasura joined the Unicorn Club on Feb 22, 2022...",Greenoaks,Cloud-based graphql API development platform. ...,2017,San Francisco,United States,Series C,...,5 years 1 month,Lightspeed Venture Partners,Nexus Venture Partners,"?11.4K as on Mar 31, 2024","$1B as on Apr 22, 2025",$239M,NaN,"Series C, Feb 22, 2022, $100M",2022,<NA>
49,69,Licious,https://tracxn.com/d/companies/licious/__LHekQ...,"Licious joined the Unicorn Club on Oct 05, 202...",Avendus,Platform offering meat and seafood delivery. I...,2015,Bengaluru,India,Series G,...,6 years 9 months,True North,Temasek,"?748Cr as on Mar 31, 2024","?12,100Cr as on Sep 21, 2023",$490M,NaN,"Series G, Sep 21, 2023, $914K",2022,<NA>
54,64,Eruditus,https://tracxn.com/d/companies/eruditus/__WyGE...,"Eruditus joined the Unicorn Club on Aug 12, 20...",Accel,Provider of executive-level programs for profe...,2010,Singapore,Singapore,Series F,...,11 years 7 months,CPP Investments,TPG,"$405M as on Jun 30, 2023","$3.1B as on Oct 18, 2024",$961M,NaN,"Series F, Oct 18, 2024, $150M",2022,<NA>
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,...,10 years 5 months,Unknown,Unknown,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025",2020,<NA>
89,29,FirstCry,https://tracxn.com/d/companies/firstcry/__wxnu...,"FirstCry joined the Unicorn Club on Feb 07, 2020",Unknown,Online retailer offering multi-category baby p...,2010,Pune,India,Public,...,10 years 1 month,ChrysCapital,New Enterprise Associates,$513M,"6,895 as on Sep 30, 2024",NaN,NaN,"Series E, Mar 27, 2021, $13.1M",2020,<NA>
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,...,23 years 3 months,Enterprise Collaboration,Customer Service Software,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025",2019,<NA>
104,14,Policybazaar,https://tracxn.com/d/companies/policybazaar/__...,Policybazaar joined the Unicorn Club on Jun 25...,Unknown,"Online platform for insurance buyers in India,...",2008,Gurugram,India,Late Stage,...,10 years 5 months,Premji Invest,Burman Family Holdings,"?3,820Cr as on Mar 31, 2024","22,635 as on Feb 28, 2025",NaN,NaN,"Post IPO, Oct 14, 2017, $7.69M",2018,<NA>
109,9,Hike,https://tracxn.com/d/companies/hike/__qZyenG-G...,"Hike joined the Unicorn Club on Aug 16, 2016 a...",Tencent,Provider of a blockchain-based mobile gaming p...,2012,Delhi,India,Series D,...,4 years 7 months,Non Fungible Tokens,Foxconn Electronics,"$46.8M as on Mar 31, 2024","$1.4B as on Aug 17, 2016",$261M,NaN,"Series D, May 06, 2022",2017,<NA>
117,1,InMobi,https://tracxn.com/d/companies/inmobi/__KZsV2N...,"InMobi joined the Unicorn Club on Sep 15, 2011...",SoftBank Vision Fund,Platform offering mobile ad network software. ...,2007,Bengaluru,India,Series D,...,4 years 8 months,Hercules Capital,Klenier Perkins,"$268M as on Mar 31, 2023","$1.5B as on Aug 07, 2014",$266M,NaN,"Conventional Debt, Sep 11, 2024, $100M",2012,<NA>

In [129]:
df['employee_count_date'] = pd.to_datetime(df['employee_count_date'], errors='coerce')

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), int64(2), object(17)
memory usage: 19.6+ KB

In [131]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,time_to_unicorn,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,13 years 3 months,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,10 years 8 months,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,11 years 7 months,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,9 years 6 months,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,10 years 4 months,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28

In [245]:
# Extract employee count string before 'as on'
df['employee_count_number'] = df['employee_count'].apply(
     lambda x: int(re.search(r'([\d,]+)\s+as on', str(x)).group(1).replace(',', ''))
    if isinstance(x, str) and re.search(r'([\d,]+)\s+as on', str(x))
    else pd.NA
).astype('Int64')

In [172]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
 21  employee_count_number    103 non-null    Int64
dtypes: Int64(2), datetime64[ns](1), int64(2), object(17)
memory usage: 20.6+ KB

In [174]:
df[df['employee_count'].notna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,Accel,Nexus Venture Partners,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,WestBridge Capital,Invus,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,6,Paytm,https://tracxn.com/d/companies/paytm/__fX4oqtQ...,"Paytm joined the Unicorn Club on Sep 29, 2015 ...",Alibaba Group,Wallet-enabled payment processing solution for...,2000,Noida,India,Public,...,Berkshire Hathaway,T. Rowe Price,"?10,500Cr as on Mar 31, 2024",$3.48B,NaN,"5 as on Feb 28, 2025","Angel, Nov 20, 2020, $1.26M",2016,2025-02-28,5
113,5,Quikr,https://tracxn.com/d/companies/quikr/__DlO73-L...,"Quikr joined the Unicorn Club on Apr 07, 2015 ...",Steadview,Online classifieds portal for multi-category s...,2008,Bengaluru,India,Series H,...,Warburg Pincus,NGP Capital,"?53.4Cr as on Mar 31, 2023","$566M as on Feb 19, 2020",$370M,"74 as on Feb 28, 2025","Angel, Jul 25, 2019, $100K",2015,2025-02-28,74
114,4,Snapdeal,https://platform.tracxn.com/a/d/company/hIjt4a...,"Snapdeal joined the Unicorn Club on May 20, 2014",Unknown,Online marketplace platform offering fashion a...,2010,Delhi,India,Series H,...,New Enterprise Associates,BlackRock,"?385Cr as on Mar 31, 2024","$4.8B as on Aug 02, 2015",$1.77B,"277 as on Mar 31, 2025","Angel, Jul 23, 2019",2014,2025-03-31,277
115,3,Mu Sigma,https://tracxn.com/d/companies/mu-sigma/___wjw...,"Mu Sigma joined the Unicorn Club on Feb 28, 20...",Mastercard,Visual data analytics platform for enterprises...,2004,Northbrook,United States,Series C,...,Big Data Analytics,General Atlantic,"?899Cr as on Mar 31, 2024","$1B as on Feb 28, 2013",$215M,"2,312 as on Sep 30, 2024","Series C, Apr 18, 2024, $2.01M",2013,2024-09-30,2312
116,2,Flipkart,https://tracxn.com/d/companies/flipkart/__pEY5...,"Flipkart joined the Unicorn Club on Aug 24, 2012",Unknown,Online marketplace platform offering multi-cat...,2007,Bengaluru,India,Acquired,...,CPP Investments,Vulcan Capital,"?70,800Cr as on Mar 31, 2024","$36B as on May 25, 2024",$12.1B,"7,129 as on Feb 28, 2025","Series J, May 25, 2024, $350M",2013,2025-02-28,7129

In [153]:
df[df['employee_count_number'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,top_investors_1,top_investors_2,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,Wellington,Kedaara,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,<NA>
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,Herald Investment Management,GIC,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,<NA>
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,Wellington,Lightstone Ventures,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,<NA>
5,113,Perfios,https://tracxn.com/d/companies/perfios/__0EGHn...,"Perfios joined the Unicorn Club on Mar 13, 202...",Ontario Teachers' Pension Plan,Provider of fintech solutions for digital onbo...,2008,Bengaluru,India,Series D,...,Alternative Lending,Investment Tech,"?569Cr as on Mar 31, 2024","?8,440Cr as on Mar 27, 2024",$263M,"1,072 as on Feb 28, 2025","Series D, Mar 13, 2024, $80M",2024,2025-02-28,<NA>
7,111,InCred,https://tracxn.com/d/companies/incred/__s4e5Bl...,"InCred joined the Unicorn Club on Nov 09, 2023...",Ranjan Pai,Online platform offering diversified consumer ...,2016,Mumbai,India,Series D,...,KKR,Barclays,"?2.71L as on Mar 31, 2024","$1.04B as on Dec 25, 2023",$318M,"2,004 as on Jan 31, 2025","Conventional Debt, Mar 13, 2025, $30M",2024,2025-01-31,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,10,Zomato,https://tracxn.com/d/companies/zomato/__2jvEgm...,"Zomato joined the Unicorn Club on Feb 01, 2018...",Ant Group,Online food discovery and ordering platform fr...,2008,Gurugram,India,Public,...,Fidelity Investments,Temasek,"?13,000Cr as on Mar 31, 2024",$1.69B,NaN,"7,536 as on Jan 31, 2025","Post IPO, Nov 28, 2024, $1B",2018,2025-01-31,<NA>
109,9,Hike,https://tracxn.com/d/companies/hike/__qZyenG-G...,"Hike joined the Unicorn Club on Aug 16, 2016 a...",Tencent,Provider of a blockchain-based mobile gaming p...,2012,Delhi,India,Series D,...,Non Fungible Tokens,Foxconn Electronics,"$46.8M as on Mar 31, 2024","$1.4B as on Aug 17, 2016",$261M,NaN,"Series D, May 06, 2022",2017,NaT,<NA>
115,3,Mu Sigma,https://tracxn.com/d/companies/mu-sigma/___wjw...,"Mu Sigma joined the Unicorn Club on Feb 28, 20...",Mastercard,Visual data analytics platform for enterprises...,2004,Northbrook,United States,Series C,...,Big Data Analytics,General Atlantic,"?899Cr as on Mar 31, 2024","$1B as on Feb 28, 2013",$215M,"2,312 as on Sep 30, 2024","Series C, Apr 18, 2024, $2.01M",2013,2024-09-30,<NA>
116,2,Flipkart,https://tracxn.com/d/companies/flipkart/__pEY5...,"Flipkart joined the Unicorn Club on Aug 24, 2012",Unknown,Online marketplace platform offering multi-cat...,2007,Bengaluru,India,Acquired,...,CPP Investments,Vulcan Capital,"?70,800Cr as on Mar 31, 2024","$36B as on May 25, 2024",$12.1B,"7,129 as on Feb 28, 2025","Series J, May 25, 2024, $350M",2013,2025-02-28,<NA>
117,1,InMobi,https://tracxn.com/d/companies/inmobi/__KZsV2N...,"InMobi joined the Unicorn Club on Sep 15, 2011...",SoftBank Vision Fund,Platform offering mobile ad network software. ...,2007,Bengaluru,India,Series D,...,Hercules Capital,Klenier Perkins,"$268M as on Mar 31, 2023","$1.5B as on Aug 07, 2014",$266M,NaN,"Conventional Debt, Sep 11, 2024, $100M",2012,NaT,<NA>

In [180]:
df[['latest_funding_round', 'stage']].iloc[25:60]

                       latest_funding_round     stage
25            Series E, Jan 28, 2022, $400M  Series E
26             Series G, Nov 07, 2023, $80M  Series G
27            Series E, Feb 07, 2022, $330M  Series E
28                   Series F, Feb 29, 2024  Series F
29            Series E, Jan 27, 2022, $210M  Series E
30            Series D, Mar 05, 2025, $140M  Series D
31           Series E, Jan 04, 2024, $1.14M  Series E
32            Series E, Jan 05, 2022, $360M  Series E
33               Angel, Sep 13, 2022, $755K    Public
34  Conventional Debt, Feb 06, 2024, $18.1M  Series B
35            Series E, Dec 07, 2021, $100M  Series E
36  Conventional Debt, Jul 19, 2024, $7.77M  Series C
37            Series E, Mar 13, 2025, $110M  Series E
38              Series E, Mar 01, 2023, $5M  Series E
39               Angel, May 07, 2024, $802K  Series B
40           Series F, Oct 27, 2023, $10.2M  Series F
41    Conventional Debt, Sep 28, 2021, $21M  Series C
42                   Series C, Sep 16, 2022  Series C
43            Series E, May 25, 2023, $137M  Series E
44                   Series F, May 10, 2022  Series F
45     Conventional Debt, Mar 28, 2024, $6M    Public
46             Series C, Dec 11, 2024, $60M  Series C
47             Series G, Apr 22, 2025, $25M  Series G
48            Series C, Oct 06, 2021, $260M  Series C
49            Series G, Sep 21, 2023, $914K  Series G
50            Series E, Sep 27, 2024, $209K  Series E
51            Series C, Sep 15, 2021, $100M  Series C
52           Series E, Aug 21, 2023, $2.61M  Series E
53             Series F, Dec 12, 2024, $70M  Series F
54            Series F, Oct 18, 2024, $150M  Series F
55            Series D, Mar 29, 2022, $135M  Series D
56             Series C, Oct 21, 2024, $60M  Series C
57            Series E, Aug 05, 2021, $100M  Series E
58           Series G, Apr 16, 2025, $11.7M  Series G
59    Conventional Debt, May 07, 2025, $15M  Series E

In [222]:
df['annual_revenue_amount'] = df['annual_revenue'].apply(
    lambda x: re.search(r'[₹$]?\d[\d,]*[CLMBK]r?', str(x)).group(0)
    if isinstance(x, str) and re.search(r'[₹$]?\d[\d,]*[CLMBK]r?', str(x))
    else pd.NA
)

In [223]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015,348Cr,"3,450Cr"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709,"1,390Cr","10,100Cr"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630,"1,790Cr",$502M
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671,695Cr,"9,230Cr"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041,"2,770Cr",$1B

In [224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
 21  employee_count_number    103 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
dtypes: Int64(2), datetime64[ns](1), int64(2), object(19)
memory usage: 22.5+ KB

In [234]:
df['valuation_amount'] = df['valuation'].apply(
    lambda x: re.search(r'[₹$]?\d[\d,]*[CLMBK]r?', str(x)).group(0)
    if isinstance(x, str) and re.search(r'[₹$]?\d[\d,]*[CLMBK]r?', str(x))
    else pd.NA
)

In [235]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
 21  employee_count_number    103 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
dtypes: Int64(2), datetime64[ns](1), int64(2), object(19)
memory usage: 22.5+ KB

In [219]:
df[df['valuation_amount'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,...,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025",2020,NaT,<NA>,6B,<NA>
89,29,FirstCry,https://tracxn.com/d/companies/firstcry/__wxnu...,"FirstCry joined the Unicorn Club on Feb 07, 2020",Unknown,Online retailer offering multi-category baby p...,2010,Pune,India,Public,...,$513M,"6,895 as on Sep 30, 2024",NaN,NaN,"Series E, Mar 27, 2021, $13.1M",2020,NaT,<NA>,$513M,<NA>
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,...,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025",2019,NaT,<NA>,"?48,900Cr",<NA>
104,14,Policybazaar,https://tracxn.com/d/companies/policybazaar/__...,Policybazaar joined the Unicorn Club on Jun 25...,Unknown,"Online platform for insurance buyers in India,...",2008,Gurugram,India,Late Stage,...,"?3,820Cr as on Mar 31, 2024","22,635 as on Feb 28, 2025",NaN,NaN,"Post IPO, Oct 14, 2017, $7.69M",2018,NaT,<NA>,"?3,820Cr",<NA>

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
 21  employee_count_number    103 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
dtypes: Int64(2), datetime64[ns](1), int64(2), object(19)
memory usage: 22.5+ KB

In [230]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,"?348Cr as on Mar 31, 2024","?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015,348Cr,"3,450Cr"
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,"?1,390Cr as on Mar 31, 2024","?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709,"1,390Cr","10,100Cr"
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,"?1,790Cr as on Mar 31, 2024",$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630,"1,790Cr",$502M
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,"?695Cr as on Mar 31, 2024","?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671,695Cr,"9,230Cr"
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,"?2,770Cr as on Mar 31, 2024","$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041,"2,770Cr",$1B

In [231]:
df[df['valuation_amount'].isna()]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,...,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025",2020,NaT,<NA>,6B,<NA>
89,29,FirstCry,https://tracxn.com/d/companies/firstcry/__wxnu...,"FirstCry joined the Unicorn Club on Feb 07, 2020",Unknown,Online retailer offering multi-category baby p...,2010,Pune,India,Public,...,$513M,"6,895 as on Sep 30, 2024",NaN,NaN,"Series E, Mar 27, 2021, $13.1M",2020,NaT,<NA>,$513M,<NA>
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,...,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025",2019,NaT,<NA>,"48,900Cr",<NA>
104,14,Policybazaar,https://tracxn.com/d/companies/policybazaar/__...,Policybazaar joined the Unicorn Club on Jun 25...,Unknown,"Online platform for insurance buyers in India,...",2008,Gurugram,India,Late Stage,...,"?3,820Cr as on Mar 31, 2024","22,635 as on Feb 28, 2025",NaN,NaN,"Post IPO, Oct 14, 2017, $7.69M",2018,NaT,<NA>,"3,820Cr",<NA>

In [249]:
median_emp_count = df['employee_count_number'].median()

In [252]:
median_emp_count = int(median_emp_count)
median_emp_count

914

In [253]:
df['employee_count_number'].fillna(median_emp_count, inplace = True)

<ipython-input-253-1341745782>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['employee_count_number'].fillna(median_emp_count, inplace = True)

In [254]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      103 non-null    datetime64[ns]
 21  employee_count_number    118 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
dtypes: Int64(2), datetime64[ns](1), int64(2), object(19)
memory usage: 22.5+ KB

In [261]:
df[df['employee_count_number']== 914]

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,annual_revenue,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount
9,109,boAt,https://tracxn.com/d/companies/boat/__1-6OVEvW...,"boAt joined the Unicorn Club on Oct 28, 2022 a...",Warburg Pincus,Platform offering wearable audio devices. Its ...,2016,Gurugram,India,Series C,...,"?10,800Cr as on Dec 02, 2022",$171M,"952 as on Feb 28, 2025",NaN,"Angel, Feb 01, 2024",2023,2025-02-28,914,"10,800Cr",$171M
13,105,OneCard,https://tracxn.com/d/companies/onecard/__wf9zb...,"OneCard joined the Unicorn Club on Jul 04, 202...",Temasek,Provider of a premium metal credit card with a...,2019,Pune,India,Series D,...,"?11,600Cr as on Nov 18, 2024",$262M,"954 as on Jan 31, 2025",NaN,"Series D, Nov 18, 2024, $28.5M",2023,2025-02-28,914,"11,600Cr",$262M
14,104,LeadSquared,https://tracxn.com/d/companies/leadsquared/__G...,"LeadSquared joined the Unicorn Club on Jun 21,...",Unknown,Cloud based platform offering sales CRM and ma...,2011,Bengaluru,India,Series C,...,"?325Cr as on Mar 31, 2024","?7,200Cr as on Nov 03, 2022",$204M,NaN,"Series C, Jun 12, 2022, $153M",2022,2025-02-28,914,325Cr,"7,200Cr"
15,103,Purplle,https://tracxn.com/d/companies/purplle/__Xj8FM...,"Purplle joined the Unicorn Club on Jun 09, 202...",Paramark Ventures,Online cosmetic brands marketplace platform of...,2011,Mumbai,India,Series F,...,"?725Cr as on Mar 31, 2024","$1.3B as on Oct 14, 2024",$560M,"914 as on Feb 28, 2025","Series F, Jun 27, 2024, $178M",2022,2025-02-28,914,725Cr,3B
16,102,Physics Wallah,https://tracxn.com/d/companies/physics-wallah/...,Physics Wallah joined the Unicorn Club on Jun ...,WestBridge Capital,"Online platform offering live courses for JEE,...",2020,Noida,India,Series B,...,"$3.7B as on Feb 11, 2025",$312M,"11,464 as on Feb 28, 2025",NaN,"Series B, Sep 20, 2024, $210M",2022,2025-02-28,914,7B,$312M
18,100,Open,https://tracxn.com/d/companies/open/__Tivm52sB...,"Open joined the Unicorn Club on May 02, 2022 a...",India Infoline,SaaS-based digital bank for startups and enter...,2017,Bengaluru,India,Series D,...,"?7,300Cr as on Jun 01, 2022",$186M,"289 as on Mar 31, 2025",NaN,"Series D, May 02, 2022, $50M",2022,2025-02-28,914,"7,300Cr",$186M
22,96,Amagi,https://tracxn.com/d/companies/amagi/__EroEsPU...,"Amagi joined the Unicorn Club on Mar 16, 2022 ...",Accel,Cloud based CTV advertising platform for enter...,2008,Bengaluru,India,Series F,...,"?11,600Cr as on Nov 13, 2022",$359M,NaN,NaN,"Series F, Nov 01, 2022, $100M",2022,2025-02-28,914,"11,600Cr",$359M
24,94,Hasura,https://tracxn.com/d/companies/hasura/__SMK3S7...,"Hasura joined the Unicorn Club on Feb 22, 2022...",Greenoaks,Cloud-based graphql API development platform. ...,2017,San Francisco,United States,Series C,...,"?11.4K as on Mar 31, 2024","$1B as on Apr 22, 2025",$239M,NaN,"Series C, Feb 22, 2022, $100M",2022,2025-02-28,914,4K,$1B
49,69,Licious,https://tracxn.com/d/companies/licious/__LHekQ...,"Licious joined the Unicorn Club on Oct 05, 202...",Avendus,Platform offering meat and seafood delivery. I...,2015,Bengaluru,India,Series G,...,"?748Cr as on Mar 31, 2024","?12,100Cr as on Sep 21, 2023",$490M,NaN,"Series G, Sep 21, 2023, $914K",2022,2025-02-28,914,748Cr,"12,100Cr"
54,64,Eruditus,https://tracxn.com/d/companies/eruditus/__WyGE...,"Eruditus joined the Unicorn Club on Aug 12, 20...",Accel,Provider of executive-level programs for profe...,2010,Singapore,Singapore,Series F,...,"$405M as on Jun 30, 2023","$3.1B as on Oct 18, 2024",$961M,NaN,"Series F, Oct 18, 2024, $150M",2022,2025-02-28,914,$405M,1B
85,33,Zerodha,https://tracxn.com/d/companies/zerodha/__Y4-fh...,"Zerodha joined the Unicorn Club on Jun 29, 2020",Unknown,Broker-based online trading and investment pla...,2010,Bengaluru,India,Unfunded,...,"$3.6B as on Sep 28, 2023",NaN,NaN,NaN,"1,228 as on Mar 31, 2025",2020,2025-02-28,914,6B,<NA>
89,29,FirstCry,https://tracxn.com/d/companies/firstcry/__wxnu...,"FirstCry joined the Unicorn Club on Feb 07, 2020",Unknown,Online retailer offering multi-category baby p...,2010,Pune,India,Public,...,$513M,"6,895 as on Sep 30, 2024",NaN,NaN,"Series E, Mar 27, 2021, $13.1M",2020,2025-02-28,914,$513M,<NA>
97,21,Zoho,https://tracxn.com/d/companies/zoho/__nGqGUzgu...,"Zoho joined the Unicorn Club on Apr 20, 2019",Unknown,Provider of enterprise collaboration and HR ma...,1996,Chennai,India,Unfunded,...,"?48,900Cr as on Dec 06, 2022",NaN,NaN,NaN,"34,180 as on Jan 31, 2025",2019,2025-02-28,914,"48,900Cr",<NA>
104,14,Policybazaar,https://tracxn.com/d/companies/policybazaar/__...,Policybazaar joined the Unicorn Club on Jun 25...,Unknown,"Online platform for insurance buyers in India,...",2008,Gurugram,India,Late Stage,...,"?3,820Cr as on Mar 31, 2024","22,635 as on Feb 28, 2025",NaN,NaN,"Post IPO, Oct 14, 2017, $7.69M",2018,2025-02-28,914,"3,820Cr",<NA>
109,9,Hike,https://tracxn.com/d/companies/hike/__qZyenG-G...,"Hike joined the Unicorn Club on Aug 16, 2016 a...",Tencent,Provider of a blockchain-based mobile gaming p...,2012,Delhi,India,Series D,...,"$46.8M as on Mar 31, 2024","$1.4B as on Aug 17, 2016",$261M,NaN,"Series D, May 06, 2022",2017,2025-02-28,914,8M,4B
117,1,InMobi,https://tracxn.com/d/companies/inmobi/__KZsV2N...,"InMobi joined the Unicorn Club on Sep 15, 2011...",SoftBank Vision Fund,Platform offering mobile ad network software. ...,2007,Bengaluru,India,Series D,...,"$268M as on Mar 31, 2023","$1.5B as on Aug 07, 2014",$266M,NaN,"Conventional Debt, Sep 11, 2024, $100M",2012,2025-02-28,914,$268M,5B

In [258]:
median_emp_date = df['employee_count_date'].median()
median_emp_date

Timestamp('2025-02-28 00:00:00')

In [259]:
df['employee_count_date'].fillna(median_emp_date, inplace =True)

<ipython-input-259-67123532>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['employee_count_date'].fillna(median_emp_date, inplace =True)

In [260]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      118 non-null    datetime64[ns]
 21  employee_count_number    118 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
dtypes: Int64(2), datetime64[ns](1), int64(2), object(19)
memory usage: 22.5+ KB

TypeError: Cannot convert ['$88M' '$220M' nan '$559M' '$151M' '$263M' '$51.1M' '$318M' '$1.95B'
 '952 as on Feb 28, 2025' '$124M' '$231M' '$349M' '954 as on Jan 31, 2025'
 '$204M' '$560M' '11,464 as on Feb 28, 2025' '$205M'
 '289 as on Mar 31, 2025' nan '$201M' '$196M' nan '$239M' '$239M' '$657M'
 nan '$462M' '$527M' '$387M' '$280M' '$172M' '$685M' nan '$186M' '$181M'
 '$342M' '$631M' '$368M' '$207M' '$665M' nan '$220M' nan '$688M' nan nan
 nan '$302M' '$490M' '$326M' nan '$396M' '$768M' '$961M' '$247M' '$329M'
 '$281M' nan '$604M' '$344M' nan '$757M' '$253M' '$390M' '$471M' '$376M'
 '$475M' nan '$484M' '$393M' '$867M' '$1.36B' nan '$592M' '$675M' nan
 '$2.01B' '$390M' nan '$1.01B' '$1.08B' '$410M' '$742M' '$880M' nan nan
 '$3.47B' nan nan '$1.32B' '$1.08B' '$314M' nan '$1.07B' nan '$475M' nan
 '$100M' '$943M' nan '$186M' '$1.95B' nan nan nan nan '$817M' nan '$261M'
 '$249M' '$3.84B' nan '$370M' '$1.77B' '$215M' '$12.1B' '$266M'] to numeric

In [266]:
def convert_to_number(x):
    if isinstance(x, str):
        x = x.replace(',', '').strip()
        match = re.match(r'[₹$?]?([\d\.]+)\s*(K|M|B|Cr|L)', x)
        if match:
            num = float(match.group(1))
            unit = match.group(2)

            multiplier = {
                'K': 1_000,
                'M': 1_000_000,
                'B': 1_000_000_000,
                'Cr': 10_000_000,
                'L': 100_000,
            }.get(unit, 1)

            return int(num * multiplier)

    return pd.NA

In [267]:
df['Total_funding'] = df['total_funding_till_date'].apply(convert_to_number).astype('Int64')

In [269]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,valuation,total_funding_till_date,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount,Total_funding
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,"?3,450Cr as on Jun 23, 2022",$88M,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015,348Cr,"3,450Cr",88000000
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,"?10,100Cr as on Sep 17, 2024",$220M,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709,"1,390Cr","10,100Cr",220000000
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,$502M,NaN,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630,"1,790Cr",$502M,<NA>
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,"?9,230Cr as on Dec 27, 2024",$559M,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671,695Cr,"9,230Cr",559000000
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,"$1B as on May 17, 2024",$151M,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041,"2,770Cr",$1B,151000000

In [271]:
median_total_fund = df["Total_funding"].median()
int(median_total_fund)

390000000

In [272]:
df['Total_funding'].fillna(median_total_fund, inplace = True)

<ipython-input-272-1405078626>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_funding'].fillna(median_total_fund, inplace = True)

In [273]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      118 non-null    datetime64[ns]
 21  employee_count_number    118 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
 24  Total_funding            118 non-null    Int64
dtypes: Int64(3), datetime64[ns](1), int64(2), object(19)
memory usage: 23.5+ KB

In [274]:
df['Annual_Revenue'] = df['annual_revenue_amount'].apply(convert_to_number).astype('Int64')
df['Valuation_Amount'] = df['valuation_amount'].apply(convert_to_number).astype('Int64')

In [275]:
df.head()

,Rank,Company,company_link,company_info,round_led_by,company_background,founded_year,location,country,stage,...,employee_count,latest_funding_round,unicorn_year,employee_count_date,employee_count_number,annual_revenue_amount,valuation_amount,Total_funding,Annual_Revenue,Valuation_Amount
0,118,Juspay,https://tracxn.com/d/companies/juspay/__fDjQyo...,"Juspay joined the Unicorn Club on Apr 07, 2025...",Kedaara,Provider of a global payments operating system...,2012,Bengaluru,India,Series D,...,"1,015 as on Feb 28, 2025","Series D, Apr 07, 2025",2025,2025-02-28,1015,348Cr,"3,450Cr",88000000,3480000000,34500000000
1,117,Money View,https://tracxn.com/d/companies/money-view/__NR...,"Money View joined the Unicorn Club on Sep 12, ...",Accel,Provider of digital financial services includi...,2014,Bengaluru,India,Series E,...,"709 as on Feb 28, 2025","Series E, Sep 12, 2024, $4.65M",2025,2025-02-28,709,"1,390Cr","10,100Cr",220000000,13900000000,101000000000
2,116,Ather Energy,https://tracxn.com/d/companies/ather-energy/__...,Ather Energy joined the Unicorn Club on Aug 13...,NIIF,Electric vehicle manufacturer offering scooter...,2013,Bengaluru,India,Public,...,"1,630 as on Mar 31, 2025","Series E, Aug 13, 2024, $71.5M",2025,2025-03-31,1630,"1,790Cr",$502M,390000000,17900000000,502000000
3,115,Rapido,https://tracxn.com/d/companies/rapido/__u2bFpK...,"Rapido joined the Unicorn Club on Jul 29, 2024",Unknown,"Platform offering bike taxi, auto rickshaw, an...",2015,Bengaluru,India,Series E,...,"671 as on Feb 28, 2025","Series E, Dec 27, 2024, $29.8M",2025,2025-02-28,671,695Cr,"9,230Cr",559000000,6950000000,92300000000
4,114,Porter,https://tracxn.com/d/companies/porter/__4hfBdL...,"Porter joined the Unicorn Club on May 16, 2024",Unknown,App-based platform offering on-demand trucking...,2014,Bengaluru,India,Series F,...,"2,041 as on Feb 28, 2025","Series F, May 08, 2025",2024,2025-02-28,2041,"2,770Cr",$1B,151000000,27700000000,1000000000

In [276]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      118 non-null    datetime64[ns]
 21  employee_count_number    118 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
 24  Total_funding            118 non-null    Int64
 25  Annual_Revenue           118 non-null    Int64
 26  Valuation_Amount         114 non-null    Int64
dtypes: Int64(5), datetime64[ns](1), int64(2), object(19)
memory usage: 25.6+ KB

In [277]:
median_valuation_amount = df['Valuation_Amount'].median()
int(median_valuation_amount)

7500000000

In [278]:
df['Valuation_Amount'].fillna(median_valuation_amount, inplace = True)

<ipython-input-278-2250676590>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Valuation_Amount'].fillna(median_valuation_amount, inplace = True)

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     118 non-null    int64
 1   Company                  118 non-null    object
 2   company_link             118 non-null    object
 3   company_info             118 non-null    object
 4   round_led_by             118 non-null    object
 5   company_background       118 non-null    object
 6   founded_year             118 non-null    int64
 7   location                 118 non-null    object
 8   country                  118 non-null    object
 9   stage                    118 non-null    object
 10  primary_sector           118 non-null    object
 11  time_to_unicorn          118 non-null    object
 12  top_investors_1          118 non-null    object
 13  top_investors_2          118 non-null    object
 14  annual_revenue           118 non-null    object
 15  valuation                116 non-null    object
 16  total_funding_till_date  87 non-null     object
 17  employee_count           103 non-null    object
 18  latest_funding_round     118 non-null    object
 19  unicorn_year             118 non-null    Int64
 20  employee_count_date      118 non-null    datetime64[ns]
 21  employee_count_number    118 non-null    Int64
 22  annual_revenue_amount    118 non-null    object
 23  valuation_amount         114 non-null    object
 24  Total_funding            118 non-null    Int64
 25  Annual_Revenue           118 non-null    Int64
 26  Valuation_Amount         118 non-null    Int64
dtypes: Int64(5), datetime64[ns](1), int64(2), object(19)
memory usage: 25.6+ KB

In [281]:
unicorn_data = df.drop(['company_link', 'company_info', 'company_background', 'time_to_unicorn', 'annual_revenue', 'valuation', 'total_funding_till_date', 'employee_count', 'latest_funding_round', 'annual_revenue_amount', 'valuation_amount'], axis = 1)

In [282]:
unicorn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   118 non-null    int64
 1   Company                118 non-null    object
 2   round_led_by           118 non-null    object
 3   founded_year           118 non-null    int64
 4   location               118 non-null    object
 5   country                118 non-null    object
 6   stage                  118 non-null    object
 7   primary_sector         118 non-null    object
 8   top_investors_1        118 non-null    object
 9   top_investors_2        118 non-null    object
 10  unicorn_year           118 non-null    Int64
 11  employee_count_date    118 non-null    datetime64[ns]
 12  employee_count_number  118 non-null    Int64
 13  Total_funding          118 non-null    Int64
 14  Annual_Revenue         118 non-null    Int64
 15  Valuation_Amount       118 non-null    Int64
dtypes: Int64(5), datetime64[ns](1), int64(2), object(8)
memory usage: 15.5+ KB

In [283]:
unicorn_data.head()

,Rank,Company,round_led_by,founded_year,location,country,stage,primary_sector,top_investors_1,top_investors_2,unicorn_year,employee_count_date,employee_count_number,Total_funding,Annual_Revenue,Valuation_Amount
0,118,Juspay,Kedaara,2012,Bengaluru,India,Series D,Payments,Wellington,Kedaara,2025,2025-02-28,1015,88000000,3480000000,34500000000
1,117,Money View,Accel,2014,Bengaluru,India,Series E,Alternative Lending,Accel,Nexus Venture Partners,2025,2025-02-28,709,220000000,13900000000,101000000000
2,116,Ather Energy,NIIF,2013,Bengaluru,India,Public,Electric Vehicles,Herald Investment Management,GIC,2025,2025-03-31,1630,390000000,17900000000,502000000
3,115,Rapido,Unknown,2015,Bengaluru,India,Series E,Road Transport Tech,WestBridge Capital,Invus,2025,2025-02-28,671,559000000,6950000000,92300000000
4,114,Porter,Unknown,2014,Bengaluru,India,Series F,Logistics Tech,Wellington,Lightstone Ventures,2024,2025-02-28,2041,151000000,27700000000,1000000000

In [284]:
unicorn_data.to_csv('Unicorn_Data.csv', index=False)

In [285]:
from google.colab import files
files.download('Unicorn_Data.csv')